var namespacenlohmann_1_1detail =
[
    [ "binary_reader", "classnlohmann_1_1detail_1_1binary__reader.html", "classnlohmann_1_1detail_1_1binary__reader" ],
    [ "binary_writer", "classnlohmann_1_1detail_1_1binary__writer.html", "classnlohmann_1_1detail_1_1binary__writer" ],
    [ "conjunction", "structnlohmann_1_1detail_1_1conjunction.html", null ],
    [ "conjunction< B1 >", "structnlohmann_1_1detail_1_1conjunction_3_01_b1_01_4.html", null ],
    [ "conjunction< B1, Bn... >", "structnlohmann_1_1detail_1_1conjunction_3_01_b1_00_01_bn_8_8_8_01_4.html", null ],
    [ "exception", "classnlohmann_1_1detail_1_1exception.html", "classnlohmann_1_1detail_1_1exception" ],
    [ "external_constructor", "structnlohmann_1_1detail_1_1external__constructor.html", null ],
    [ "external_constructor< value_t::array >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1array_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1array_01_4" ],
    [ "external_constructor< value_t::boolean >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1boolean_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1boolean_01_4" ],
    [ "external_constructor< value_t::number_float >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__float_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__float_01_4" ],
    [ "external_constructor< value_t::number_integer >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__integer_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__integer_01_4" ],
    [ "external_constructor< value_t::number_unsigned >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__unsigned_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__unsigned_01_4" ],
    [ "external_constructor< value_t::object >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1object_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1object_01_4" ],
    [ "external_constructor< value_t::string >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1string_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1string_01_4" ],
    [ "from_json_fn", "structnlohmann_1_1detail_1_1from__json__fn.html", "structnlohmann_1_1detail_1_1from__json__fn" ],
    [ "has_from_json", "structnlohmann_1_1detail_1_1has__from__json.html", "structnlohmann_1_1detail_1_1has__from__json" ],
    [ "has_non_default_from_json", "structnlohmann_1_1detail_1_1has__non__default__from__json.html", "structnlohmann_1_1detail_1_1has__non__default__from__json" ],
    [ "has_to_json", "structnlohmann_1_1detail_1_1has__to__json.html", "structnlohmann_1_1detail_1_1has__to__json" ],
    [ "index_sequence", "structnlohmann_1_1detail_1_1index__sequence.html", "structnlohmann_1_1detail_1_1index__sequence" ],
    [ "input_adapter", "classnlohmann_1_1detail_1_1input__adapter.html", "classnlohmann_1_1detail_1_1input__adapter" ],
    [ "input_adapter_protocol", "structnlohmann_1_1detail_1_1input__adapter__protocol.html", "structnlohmann_1_1detail_1_1input__adapter__protocol" ],
    [ "input_buffer_adapter", "classnlohmann_1_1detail_1_1input__buffer__adapter.html", "classnlohmann_1_1detail_1_1input__buffer__adapter" ],
    [ "input_stream_adapter", "classnlohmann_1_1detail_1_1input__stream__adapter.html", "classnlohmann_1_1detail_1_1input__stream__adapter" ],
    [ "internal_iterator", "structnlohmann_1_1detail_1_1internal__iterator.html", "structnlohmann_1_1detail_1_1internal__iterator" ],
    [ "invalid_iterator", "classnlohmann_1_1detail_1_1invalid__iterator.html", "classnlohmann_1_1detail_1_1invalid__iterator" ],
    [ "is_basic_json", "structnlohmann_1_1detail_1_1is__basic__json.html", null ],
    [ "is_basic_json< NLOHMANN_BASIC_JSON_TPL >", "structnlohmann_1_1detail_1_1is__basic__json_3_01_n_l_o_h_m_a_n_n___b_a_s_i_c___j_s_o_n___t_p_l_01_4.html", null ],
    [ "is_basic_json_nested_type", "structnlohmann_1_1detail_1_1is__basic__json__nested__type.html", "structnlohmann_1_1detail_1_1is__basic__json__nested__type" ],
    [ "is_compatible_array_type", "structnlohmann_1_1detail_1_1is__compatible__array__type.html", "structnlohmann_1_1detail_1_1is__compatible__array__type" ],
    [ "is_compatible_integer_type", "structnlohmann_1_1detail_1_1is__compatible__integer__type.html", "structnlohmann_1_1detail_1_1is__compatible__integer__type" ],
    [ "is_compatible_integer_type_impl", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl.html", null ],
    [ "is_compatible_integer_type_impl< true, RealIntegerType, CompatibleNumberIntegerType >", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01true_00_01_real_integer_type78b0ba77f36a8c8169cdb79b01d1a4bf.html", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01true_00_01_real_integer_type78b0ba77f36a8c8169cdb79b01d1a4bf" ],
    [ "is_compatible_object_type", "structnlohmann_1_1detail_1_1is__compatible__object__type.html", "structnlohmann_1_1detail_1_1is__compatible__object__type" ],
    [ "is_compatible_object_type_impl", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl.html", null ],
    [ "is_compatible_object_type_impl< true, RealType, CompatibleObjectType >", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl_3_01true_00_01_real_type_00_01_compatible_object_type_01_4.html", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl_3_01true_00_01_real_type_00_01_compatible_object_type_01_4" ],
    [ "iter_impl", "classnlohmann_1_1detail_1_1iter__impl.html", "classnlohmann_1_1detail_1_1iter__impl" ],
    [ "iteration_proxy", "classnlohmann_1_1detail_1_1iteration__proxy.html", "classnlohmann_1_1detail_1_1iteration__proxy" ],
    [ "json_ref", "classnlohmann_1_1detail_1_1json__ref.html", "classnlohmann_1_1detail_1_1json__ref" ],
    [ "json_reverse_iterator", "classnlohmann_1_1detail_1_1json__reverse__iterator.html", "classnlohmann_1_1detail_1_1json__reverse__iterator" ],
    [ "lexer", "classnlohmann_1_1detail_1_1lexer.html", "classnlohmann_1_1detail_1_1lexer" ],
    [ "make_index_sequence", "structnlohmann_1_1detail_1_1make__index__sequence.html", null ],
    [ "make_index_sequence< 0 >", "structnlohmann_1_1detail_1_1make__index__sequence_3_010_01_4.html", null ],
    [ "make_index_sequence< 1 >", "structnlohmann_1_1detail_1_1make__index__sequence_3_011_01_4.html", null ],
    [ "merge_and_renumber", "structnlohmann_1_1detail_1_1merge__and__renumber.html", null ],
    [ "merge_and_renumber< index_sequence< I1... >, index_sequence< I2... > >", "structnlohmann_1_1detail_1_1merge__and__renumber_3_01index__sequence_3_01_i1_8_8_8_01_4_00_01indf5ec8c9c7b5107e4b381e3ca4c1be2ca.html", null ],
    [ "negation", "structnlohmann_1_1detail_1_1negation.html", null ],
    [ "other_error", "classnlohmann_1_1detail_1_1other__error.html", "classnlohmann_1_1detail_1_1other__error" ],
    [ "out_of_range", "classnlohmann_1_1detail_1_1out__of__range.html", "classnlohmann_1_1detail_1_1out__of__range" ],
    [ "output_adapter", "classnlohmann_1_1detail_1_1output__adapter.html", "classnlohmann_1_1detail_1_1output__adapter" ],
    [ "output_adapter_protocol", "structnlohmann_1_1detail_1_1output__adapter__protocol.html", "structnlohmann_1_1detail_1_1output__adapter__protocol" ],
    [ "output_stream_adapter", "classnlohmann_1_1detail_1_1output__stream__adapter.html", "classnlohmann_1_1detail_1_1output__stream__adapter" ],
    [ "output_string_adapter", "classnlohmann_1_1detail_1_1output__string__adapter.html", "classnlohmann_1_1detail_1_1output__string__adapter" ],
    [ "output_vector_adapter", "classnlohmann_1_1detail_1_1output__vector__adapter.html", "classnlohmann_1_1detail_1_1output__vector__adapter" ],
    [ "parse_error", "classnlohmann_1_1detail_1_1parse__error.html", "classnlohmann_1_1detail_1_1parse__error" ],
    [ "parser", "classnlohmann_1_1detail_1_1parser.html", "classnlohmann_1_1detail_1_1parser" ],
    [ "primitive_iterator_t", "classnlohmann_1_1detail_1_1primitive__iterator__t.html", "classnlohmann_1_1detail_1_1primitive__iterator__t" ],
    [ "priority_tag", "structnlohmann_1_1detail_1_1priority__tag.html", null ],
    [ "priority_tag< 0 >", "structnlohmann_1_1detail_1_1priority__tag_3_010_01_4.html", null ],
    [ "serializer", "classnlohmann_1_1detail_1_1serializer.html", "classnlohmann_1_1detail_1_1serializer" ],
    [ "static_const", "structnlohmann_1_1detail_1_1static__const.html", "structnlohmann_1_1detail_1_1static__const" ],
    [ "to_json_fn", "structnlohmann_1_1detail_1_1to__json__fn.html", "structnlohmann_1_1detail_1_1to__json__fn" ],
    [ "type_error", "classnlohmann_1_1detail_1_1type__error.html", "classnlohmann_1_1detail_1_1type__error" ]
];